export const RELATED_TOOLS_MAP: Record<string, { name: string; href: string; description: string }[]> = {
  // ── PDF: Core workflow ─────────────────────────────────────
  "compress-pdf": [
    { name: "Merge PDF", href: "/merge-pdf", description: "Combine multiple PDFs into one document" },
    { name: "Split PDF", href: "/split-pdf", description: "Divide PDF by page ranges or extract pages" },
    { name: "PDF to Word", href: "/pdf-to-word", description: "Convert PDF to editable DOCX" },
    { name: "PDF Editor", href: "/pdf-editor", description: "Draw, highlight, add text on PDF pages" },
    { name: "PDF Roast & Quality Score", href: "/pdf-roast", description: "Get a quality score for your PDF" },
    { name: "Why Is My PDF So Big?", href: "/size-analyzer", description: "Diagnose what is making your PDF large" },
  ],
  "pdf-to-jpg": [
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "PDF to PNG", href: "/pdf-to-png", description: "Convert PDF pages to PNG images" },
    { name: "PDF to WebP", href: "/pdf-to-webp", description: "Convert PDF to web-optimized WebP" },
    { name: "Image to PDF", href: "/image-to-pdf", description: "Convert images into one PDF document" },
    { name: "JPG to PDF", href: "/jpg-to-pdf", description: "Convert JPG or JPEG images to PDF" },
    { name: "Extract Images from PDF", href: "/extract-images-pdf", description: "Pull embedded images from PDFs" },
  ],
  "merge-pdf": [
    { name: "Compress PDF", href: "/compress-pdf", description: "Reduce PDF file size without losing quality" },
    { name: "Split PDF", href: "/split-pdf", description: "Divide PDF by page ranges or extract pages" },
    { name: "Organize PDF", href: "/organize-pdf", description: "Reorder, delete & duplicate PDF pages" },
    { name: "Add Page Numbers", href: "/page-numbers", description: "Insert page numbers in any position" },
    { name: "PDF Editor", href: "/pdf-editor", description: "Draw, highlight, add text on PDF pages" },
  ],
  "pdf-to-word": [
    { name: "PDF to Excel", href: "/pdf-to-excel", description: "Convert PDF tables to XLSX" },
    { name: "PDF OCR", href: "/pdf-ocr", description: "Make scanned PDFs searchable with Tesseract" },
    { name: "Word to PDF", href: "/word-to-pdf", description: "Convert Word DOCX to PDF in browser" },
    { name: "DOC to PDF", href: "/doc-to-pdf", description: "Convert Word DOC to PDF" },
    { name: "Compress PDF", href: "/compress-pdf", description: "Reduce PDF file size without losing quality" },
    { name: "PDF Editor", href: "/pdf-editor", description: "Draw, highlight, add text on PDF pages" },
  ],
  "pdf-to-excel": [
    { name: "PDF to Word", href: "/pdf-to-word", description: "Convert PDF to editable DOCX" },
    { name: "PDF to CSV", href: "/pdf-to-csv", description: "Extract PDF content as CSV" },
    { name: "PDF to Data", href: "/pdf-to-data", description: "Convert PDF to JSON or CSV structured data" },
    { name: "Excel to PDF", href: "/excel-to-pdf", description: "Convert Excel XLSX to PDF" },
    { name: "CSV to PDF", href: "/csv-to-pdf", description: "Convert CSV data to PDF table" },
    { name: "PDF OCR", href: "/pdf-ocr", description: "Make scanned PDFs searchable with Tesseract" },
  ],
  "sign-pdf": [
    { name: "PDF Editor", href: "/pdf-editor", description: "Draw, highlight, add text on PDF pages" },
    { name: "Protect PDF", href: "/protect-pdf", description: "Add password encryption to PDF" },
    { name: "PDF Form Filler", href: "/pdf-form-filler", description: "Fill PDF form fields without Adobe" },
    { name: "Flatten PDF", href: "/flatten-pdf", description: "Merge form fields into static content" },
    { name: "Watermark PDF", href: "/watermark-pdf", description: "Add custom text watermarks to PDF" },
  ],
  "unlock-pdf": [
    { name: "Protect PDF", href: "/protect-pdf", description: "Add password encryption to PDF" },
    { name: "PDF Editor", href: "/pdf-editor", description: "Draw, highlight, add text on PDF pages" },
    { name: "Compress PDF", href: "/compress-pdf", description: "Reduce PDF file size without losing quality" },
    { name: "Sign PDF", href: "/sign-pdf", description: "Add your signature to any PDF document" },
  ],
  "protect-pdf": [
    { name: "Unlock PDF", href: "/unlock-pdf", description: "Remove PDF password protection" },
    { name: "Redact PDF", href: "/redact-pdf", description: "Permanently black out sensitive information" },
    { name: "Sign PDF", href: "/sign-pdf", description: "Add your signature to any PDF document" },
    { name: "Watermark PDF", href: "/watermark-pdf", description: "Add custom text watermarks to PDF" },
  ],
  "split-pdf": [
    { name: "Merge PDF", href: "/merge-pdf", description: "Combine multiple PDFs into one document" },
    { name: "Organize PDF", href: "/organize-pdf", description: "Reorder, delete & duplicate PDF pages" },
    { name: "Compress PDF", href: "/compress-pdf", description: "Reduce PDF file size without losing quality" },
    { name: "Extract Images from PDF", href: "/extract-images-pdf", description: "Pull embedded images from PDFs" },
    { name: "Crop PDF", href: "/crop-pdf", description: "Trim PDF page margins & white space" },
  ],
  "pdf-ocr": [
    { name: "PDF to Text", href: "/pdf-to-text", description: "Extract text from PDF files" },
    { name: "PDF to Word", href: "/pdf-to-word", description: "Convert PDF to editable DOCX" },
    { name: "Image to Text", href: "/image-to-text", description: "Extract text from images using OCR" },
    { name: "Screenshot to Text", href: "/screenshot-to-text", description: "Extract text from screenshots using OCR" },
    { name: "Smart PDF Cleaner", href: "/pdf-cleaner", description: "Auto remove margins, center content & normalize fonts" },
  ],
  // ── Image: Core workflow ───────────────────────────────────
  "compress-image": [
    { name: "Resize Image", href: "/resize-image", description: "Scale image dimensions to any target size" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
    { name: "Background Remover", href: "/remove-bg", description: "Remove image backgrounds with AI" },
    { name: "Watermark Image", href: "/watermark-image", description: "Add custom text or image watermarks to photos" },
    { name: "Compress to Exact Size", href: "/compress-to-size", description: "Compress image to exact KB or MB target" },
    { name: "Bulk Image Compressor", href: "/bulk-image-compressor", description: "Compress many images at once and download as ZIP" },
  ],
  "resize-image": [
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
    { name: "Image Cropper", href: "/crop-image", description: "Crop images with precision presets" },
    { name: "Social Media Image Resizer", href: "/social-image", description: "Presets for Instagram, Twitter, LinkedIn" },
    { name: "Bulk Image Resizer", href: "/bulk-image-resizer", description: "Resize multiple images in batch — ZIP download" },
    { name: "Product Image Resizer", href: "/product-image-resizer", description: "Resize product photos with Amazon/Shopify/Etsy presets" },
  ],
  "remove-bg": [
    { name: "Background Remover", href: "/remove-bg", description: "Remove image backgrounds with AI" },
    { name: "Blur Background", href: "/blur-background", description: "Professional bokeh effect for photos" },
    { name: "Product Background Remover", href: "/product-background-remover", description: "Remove backgrounds from product photos" },
    { name: "Bulk Background Remover", href: "/bulk-background-remover", description: "Remove backgrounds from multiple images" },
    { name: "Edit Image", href: "/edit-image", description: "Adjust, crop, filter & enhance photos" },
    { name: "Watermark Image", href: "/watermark-image", description: "Add custom text or image watermarks to photos" },
  ],
  "heic-to-jpg": [
    { name: "HEIC to PNG", href: "/heic-to-png", description: "Convert HEIC to PNG" },
    { name: "HEIC to WebP", href: "/heic-to-webp", description: "Convert HEIC to WebP" },
    { name: "HEIC to PDF", href: "/heic-to-pdf", description: "Convert iPhone HEIC photos to PDF" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
    { name: "EXIF Remover", href: "/exif-remover", description: "Strip GPS & metadata from photos" },
  ],
  "image-to-text": [
    { name: "Screenshot to Text", href: "/screenshot-to-text", description: "Extract text from screenshots using OCR" },
    { name: "Handwriting to Text", href: "/handwriting-to-text", description: "Convert handwritten notes to digital text" },
    { name: "Receipt Scanner", href: "/receipt-scanner", description: "Scan receipts and extract totals and items" },
    { name: "PDF OCR", href: "/pdf-ocr", description: "Make scanned PDFs searchable with Tesseract" },
    { name: "Table Extraction from Image", href: "/table-extraction-from-image", description: "Extract tables from images into CSV" },
    { name: "Business Card Scanner", href: "/business-card-scanner", description: "Scan business cards and extract contacts" },
  ],
  "convert-image": [
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Resize Image", href: "/resize-image", description: "Scale image dimensions to any target size" },
    { name: "PNG to JPG", href: "/png-to-jpg", description: "Convert PNG to JPG with quality control" },
    { name: "JPG to PNG", href: "/jpg-to-png", description: "Convert JPG to lossless PNG" },
    { name: "PNG to WebP", href: "/png-to-webp", description: "Convert PNG to WebP — 25-35% smaller" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
  ],
  "watermark-image": [
    { name: "Watermark PDF", href: "/watermark-pdf", description: "Add custom text watermarks to PDF" },
    { name: "Watermark Remover", href: "/watermark-remover", description: "Inpaint & remove watermarks from images" },
    { name: "Bulk Watermark Adder", href: "/bulk-watermark-adder", description: "Add watermarks to multiple images at once" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Edit Image", href: "/edit-image", description: "Adjust, crop, filter & enhance photos" },
  ],
  "blur-face": [
    { name: "Blur Background", href: "/blur-background", description: "Professional bokeh effect for photos" },
    { name: "Redact PDF", href: "/redact-pdf", description: "Permanently black out sensitive information" },
    { name: "EXIF Remover", href: "/exif-remover", description: "Strip GPS & metadata from photos" },
    { name: "Edit Image", href: "/edit-image", description: "Adjust, crop, filter & enhance photos" },
    { name: "Background Remover", href: "/remove-bg", description: "Remove image backgrounds with AI" },
  ],
  "image-to-pdf": [
    { name: "JPG to PDF", href: "/jpg-to-pdf", description: "Convert JPG or JPEG images to PDF" },
    { name: "PNG to PDF", href: "/png-to-pdf", description: "Convert PNG images to PDF" },
    { name: "PDF to JPG", href: "/pdf-to-jpg", description: "Convert PDF pages to high-quality JPG images" },
    { name: "Compress PDF", href: "/compress-pdf", description: "Reduce PDF file size without losing quality" },
    { name: "Merge PDF", href: "/merge-pdf", description: "Combine multiple PDFs into one document" },
  ],
  // ── Image: Format converters ───────────────────────────────
  "png-to-jpg": [
    { name: "JPG to PNG", href: "/jpg-to-png", description: "Convert JPG to lossless PNG" },
    { name: "PNG to WebP", href: "/png-to-webp", description: "Convert PNG to WebP — 25-35% smaller" },
    { name: "PNG to PDF", href: "/png-to-pdf", description: "Convert PNG images to PDF" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk PNG to JPG", href: "/bulk-png-to-jpg", description: "Batch convert PNG files to JPG" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
  ],
  "jpg-to-png": [
    { name: "PNG to JPG", href: "/png-to-jpg", description: "Convert PNG to JPG with quality control" },
    { name: "JPG to WebP", href: "/jpg-to-webp", description: "Convert JPG to WebP — 25-34% smaller" },
    { name: "JPG to PDF", href: "/jpg-to-pdf", description: "Convert JPG or JPEG images to PDF" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk JPG to PNG", href: "/bulk-jpg-to-png", description: "Batch convert JPG to PNG" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
  ],
  "png-to-webp": [
    { name: "JPG to WebP", href: "/jpg-to-webp", description: "Convert JPG to WebP — 25-34% smaller" },
    { name: "WebP to PNG", href: "/webp-to-png", description: "Convert WebP to PNG for compatibility" },
    { name: "PNG to JPG", href: "/png-to-jpg", description: "Convert PNG to JPG with quality control" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk PNG to WebP", href: "/bulk-png-to-webp", description: "Batch convert PNG to WebP" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
  ],
  "jpg-to-webp": [
    { name: "PNG to WebP", href: "/png-to-webp", description: "Convert PNG to WebP — 25-35% smaller" },
    { name: "WebP to JPG", href: "/webp-to-jpg", description: "Convert WebP to JPG" },
    { name: "JPG to PNG", href: "/jpg-to-png", description: "Convert JPG to lossless PNG" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk JPG to WebP", href: "/bulk-jpg-to-webp", description: "Batch convert JPG to WebP" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
  ],
  "webp-to-png": [
    { name: "PNG to WebP", href: "/png-to-webp", description: "Convert PNG to WebP — 25-35% smaller" },
    { name: "WebP to JPG", href: "/webp-to-jpg", description: "Convert WebP to JPG" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk WebP to PNG", href: "/bulk-webp-to-png", description: "Batch convert WebP to PNG" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
  ],
  "webp-to-jpg": [
    { name: "JPG to WebP", href: "/jpg-to-webp", description: "Convert JPG to WebP — 25-34% smaller" },
    { name: "WebP to PNG", href: "/webp-to-png", description: "Convert WebP to PNG for compatibility" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
  ],
  "svg-to-png": [
    { name: "PNG to SVG", href: "/png-to-svg", description: "Trace PNG to SVG vector" },
    { name: "SVG to JPG", href: "/svg-to-jpg", description: "Convert SVG to JPG" },
    { name: "SVG to WebP", href: "/svg-to-webp", description: "Convert SVG to WebP" },
    { name: "SVG to ICO", href: "/svg-to-ico", description: "Create ICO favicon from SVG" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
    { name: "Favicon Generator", href: "/favicon-generator", description: "ICO, PNG & manifest.json creator" },
  ],
  "png-to-svg": [
    { name: "SVG to PNG", href: "/svg-to-png", description: "Rasterize SVG to PNG" },
    { name: "JPG to SVG", href: "/jpg-to-svg", description: "Trace JPG to SVG vector" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
    { name: "PNG to ICO", href: "/png-to-ico", description: "Create ICO favicon from PNG" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
  ],
  "jpg-to-svg": [
    { name: "PNG to SVG", href: "/png-to-svg", description: "Trace PNG to SVG vector" },
    { name: "SVG to JPG", href: "/svg-to-jpg", description: "Convert SVG to JPG" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
    { name: "JPG to PNG", href: "/jpg-to-png", description: "Convert JPG to lossless PNG" },
    { name: "Convert Image", href: "/convert-image", description: "Switch formats — PNG, JPG, WebP, SVG" },
  ],
  "png-to-ico": [
    { name: "SVG to ICO", href: "/svg-to-ico", description: "Create ICO favicon from SVG" },
    { name: "JPG to ICO", href: "/jpg-to-ico", description: "Create ICO favicon from JPG" },
    { name: "ICO to PNG", href: "/ico-to-png", description: "Extract PNG from ICO favicon" },
    { name: "Favicon Generator", href: "/favicon-generator", description: "ICO, PNG & manifest.json creator" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
  ],
  "svg-to-ico": [
    { name: "PNG to ICO", href: "/png-to-ico", description: "Create ICO favicon from PNG" },
    { name: "JPG to ICO", href: "/jpg-to-ico", description: "Create ICO favicon from JPG" },
    { name: "ICO to SVG", href: "/ico-to-svg", description: "Convert ICO to SVG (two-step guide)" },
    { name: "Favicon Generator", href: "/favicon-generator", description: "ICO, PNG & manifest.json creator" },
    { name: "SVG to PNG", href: "/svg-to-png", description: "Rasterize SVG to PNG" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
  ],
  // ── Image: Bulk tools ──────────────────────────────────────
  "bulk-image-compressor": [
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
    { name: "Bulk Image Resizer", href: "/bulk-image-resizer", description: "Resize multiple images in batch — ZIP download" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
    { name: "Compress to Exact Size", href: "/compress-to-size", description: "Compress image to exact KB or MB target" },
    { name: "Bulk PNG to WebP", href: "/bulk-png-to-webp", description: "Batch convert PNG to WebP" },
  ],
  "bulk-image-resizer": [
    { name: "Resize Image", href: "/resize-image", description: "Scale image dimensions to any target size" },
    { name: "Bulk Image Compressor", href: "/bulk-image-compressor", description: "Compress many images at once and download as ZIP" },
    { name: "Bulk Image Converter", href: "/bulk-image-converter", description: "Convert multiple images to WebP in batch" },
    { name: "Product Image Resizer", href: "/product-image-resizer", description: "Resize product photos with Amazon/Shopify/Etsy presets" },
    { name: "Social Media Image Resizer", href: "/social-image", description: "Presets for Instagram, Twitter, LinkedIn" },
  ],
  // ── Image: Product tools ───────────────────────────────────
  "amazon-image-resizer": [
    { name: "Shopify Image Optimizer", href: "/shopify-image-optimizer", description: "Optimize images for Shopify — 2048×2048" },
    { name: "Etsy Image Resizer", href: "/etsy-image-resizer", description: "Resize product photos for Etsy listings" },
    { name: "Product Image Resizer", href: "/product-image-resizer", description: "Resize product photos with Amazon/Shopify/Etsy presets" },
    { name: "Product Background Remover", href: "/product-background-remover", description: "Remove backgrounds from product photos" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
  ],
  "shopify-image-optimizer": [
    { name: "Amazon Image Resizer", href: "/amazon-image-resizer", description: "Resize product photos to Amazon 1000×1000" },
    { name: "Etsy Image Resizer", href: "/etsy-image-resizer", description: "Resize product photos for Etsy listings" },
    { name: "Product Image Resizer", href: "/product-image-resizer", description: "Resize product photos with Amazon/Shopify/Etsy presets" },
    { name: "Product Background Remover", href: "/product-background-remover", description: "Remove backgrounds from product photos" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
  ],
  "product-image-resizer": [
    { name: "Amazon Image Resizer", href: "/amazon-image-resizer", description: "Resize product photos to Amazon 1000×1000" },
    { name: "Shopify Image Optimizer", href: "/shopify-image-optimizer", description: "Optimize images for Shopify — 2048×2048" },
    { name: "Etsy Image Resizer", href: "/etsy-image-resizer", description: "Resize product photos for Etsy listings" },
    { name: "Product Background Remover", href: "/product-background-remover", description: "Remove backgrounds from product photos" },
    { name: "Bulk Image Compressor", href: "/bulk-image-compressor", description: "Compress many images at once and download as ZIP" },
    { name: "Compress Image", href: "/compress-image", description: "Reduce image file size while keeping quality" },
  ],
  // ── Image: OCR / Text ──────────────────────────────────────
  "screenshot-to-text": [
    { name: "Image to Text", href: "/image-to-text", description: "Extract text from images using OCR" },
    { name: "Handwriting to Text", href: "/handwriting-to-text", description: "Convert handwritten notes to digital text" },
    { name: "Receipt Scanner", href: "/receipt-scanner", description: "Scan receipts and extract totals and items" },
    { name: "Table Extraction from Image", href: "/table-extraction-from-image", description: "Extract tables from images into CSV" },
    { name: "PDF OCR", href: "/pdf-ocr", description: "Make scanned PDFs searchable with Tesseract" },
  ],
  // ── Dev tools ─────────────────────────────────────────────
  "json-preview": [
    { name: "JSON ↔ CSV Converter", href: "/json-csv", description: "Bidirectional JSON/CSV conversion" },
    { name: "API Formatter", href: "/api-formatter", description: "Beautify & inspect API responses" },
    { name: "Fake Data Generator", href: "/fake-data", description: "Realistic mock & dummy data" },
    { name: "Diff Checker", href: "/diff-checker", description: "Compare text, JSON & images side by side" },
    { name: "Base64 Encode / Decode", href: "/base64", description: "Base64, URL encoding & HTML entities" },
  ],
  "password-generator": [
    { name: "QR Code Generator", href: "/qr-code", description: "QR codes for URLs, WiFi, vCards" },
    { name: "Base64 Encode / Decode", href: "/base64", description: "Base64, URL encoding & HTML entities" },
    { name: "Fake Data Generator", href: "/fake-data", description: "Realistic mock & dummy data" },
    { name: "Regex Tester", href: "/regex-tester", description: "Real-time matching, groups & cheat sheet" },
  ],
  "qr-code": [
    { name: "Barcode Generator", href: "/barcode", description: "Code128, EAN-13, UPC-A & more" },
    { name: "Favicon Generator", href: "/favicon-generator", description: "ICO, PNG & manifest.json creator" },
    { name: "Password Generator", href: "/password-generator", description: "Crypto-secure & bulk passwords" },
    { name: "Color Picker & Palette", href: "/color-picker", description: "Hex, RGB, HSL & WCAG contrast" },
  ],
  "diff-checker": [
    { name: "JSON Preview", href: "/json-preview", description: "Visualize JSON as interactive tree" },
    { name: "PDF Diff", href: "/pdf-diff", description: "Compare two PDFs side by side" },
    { name: "Regex Tester", href: "/regex-tester", description: "Real-time matching, groups & cheat sheet" },
    { name: "CSV Visual Debugger", href: "/csv-debugger", description: "Find duplicates, empty values & column issues in CSV" },
    { name: "Markdown Studio", href: "/markdown-docs", description: "Render Markdown as styled docs" },
  ],
  "base64": [
    { name: "Password Generator", href: "/password-generator", description: "Crypto-secure & bulk passwords" },
    { name: "Regex Tester", href: "/regex-tester", description: "Real-time matching, groups & cheat sheet" },
    { name: "JSON Preview", href: "/json-preview", description: "Visualize JSON as interactive tree" },
    { name: "API Formatter", href: "/api-formatter", description: "Beautify & inspect API responses" },
  ],
  "regex-tester": [
    { name: "Diff Checker", href: "/diff-checker", description: "Compare text, JSON & images side by side" },
    { name: "CSV Visual Debugger", href: "/csv-debugger", description: "Find duplicates, empty values & column issues in CSV" },
    { name: "Word Counter", href: "/word-counter", description: "Words, characters, sentences & SEO" },
    { name: "Base64 Encode / Decode", href: "/base64", description: "Base64, URL encoding & HTML entities" },
  ],
  "favicon-generator": [
    { name: "PNG to ICO", href: "/png-to-ico", description: "Create ICO favicon from PNG" },
    { name: "SVG to ICO", href: "/svg-to-ico", description: "Create ICO favicon from SVG" },
    { name: "SVG Optimizer", href: "/svg-optimizer", description: "Clean & reduce SVG file size" },
    { name: "Color Picker & Palette", href: "/color-picker", description: "Hex, RGB, HSL & WCAG contrast" },
    { name: "QR Code Generator", href: "/qr-code", description: "QR codes for URLs, WiFi, vCards" },
  ],
  "website-trust-checker": [
    { name: "Website Content Extractor", href: "/website-content-extractor", description: "Extract clean article text from any URL" },
    { name: "QR Code Generator", href: "/qr-code", description: "Generate QR codes for URLs" },
    { name: "Password Generator", href: "/password-generator", description: "Crypto-secure passwords with bulk export" },
    { name: "JSON Preview", href: "/json-preview", description: "Visualize JSON as interactive tree" },
  ],
  "website-content-extractor": [
    { name: "Website Trust Checker", href: "/website-trust-checker", description: "SSL, security headers & trust score for any URL" },
    { name: "Word Counter", href: "/word-counter", description: "Count words, reading time & keyword density" },
    { name: "Diff Checker", href: "/diff-checker", description: "Compare any two texts side by side" },
    { name: "Markdown Studio", href: "/markdown-docs", description: "Render and preview Markdown beautifully" },
  ],
};
