"use client";

import { useState, useCallback, useMemo } from "react";
import {
  PenLine,
  Shield,
  Zap,
  Download,
  Calendar,
  Hash,
  Search,
  ArrowRight,
  RotateCcw,
} from "lucide-react";
import ToolHero from "@/app/components/ToolHero";
import FileUpload from "@/app/components/FileUpload";

type RenameMode = "numbering" | "date" | "pattern" | "find-replace";

interface RenameRule {
  mode: RenameMode;
  prefix: string;
  suffix: string;
  startNumber: number;
  padding: number;
  dateFormat: string;
  findText: string;
  replaceText: string;
  pattern: string;
  keepExtension: boolean;
}

interface FileEntry {
  original: File;
  newName: string;
}

const defaultRule: RenameRule = {
  mode: "numbering",
  prefix: "file_",
  suffix: "",
  startNumber: 1,
  padding: 3,
  dateFormat: "YYYY-MM-DD",
  findText: "",
  replaceText: "",
  pattern: "{name}_{n}",
  keepExtension: true,
};

function generateNewName(originalName: string, index: number, rule: RenameRule): string {
  const ext = rule.keepExtension
    ? originalName.includes(".")
      ? "." + originalName.split(".").pop()
      : ""
    : "";
  const baseName = originalName.includes(".")
    ? originalName.substring(0, originalName.lastIndexOf("."))
    : originalName;

  switch (rule.mode) {
    case "numbering": {
      const num = String(rule.startNumber + index).padStart(rule.padding, "0");
      return `${rule.prefix}${num}${rule.suffix}${ext}`;
    }
    case "date": {
      const now = new Date();
      const dateStr = rule.dateFormat
        .replace("YYYY", String(now.getFullYear()))
        .replace("MM", String(now.getMonth() + 1).padStart(2, "0"))
        .replace("DD", String(now.getDate()).padStart(2, "0"))
        .replace("HH", String(now.getHours()).padStart(2, "0"))
        .replace("mm", String(now.getMinutes()).padStart(2, "0"))
        .replace("ss", String(now.getSeconds()).padStart(2, "0"));
      return `${rule.prefix}${dateStr}_${String(index + 1).padStart(2, "0")}${rule.suffix}${ext}`;
    }
    case "find-replace": {
      const replaced = baseName.split(rule.findText).join(rule.replaceText);
      return `${replaced}${ext}`;
    }
    case "pattern": {
      const num = String(rule.startNumber + index).padStart(rule.padding, "0");
      const now = new Date();
      const dateStr = rule.dateFormat
        .replace("YYYY", String(now.getFullYear()))
        .replace("MM", String(now.getMonth() + 1).padStart(2, "0"))
        .replace("DD", String(now.getDate()).padStart(2, "0"));
      return rule.pattern
        .replace("{name}", baseName)
        .replace("{n}", num)
        .replace("{date}", dateStr)
        .replace("{i}", String(index + 1))
        + ext;
    }
    default:
      return originalName;
  }
}

export default function BulkRenamerPage() {
  const [files, setFiles] = useState<File[]>([]);
  const [rule, setRule] = useState<RenameRule>(defaultRule);
  const [renamed, setRenamed] = useState(false);

  const previewEntries = useMemo(() => {
    return files.map((file, i) => ({
      original: file.name,
      newName: generateNewName(file.name, i, rule),
    }));
  }, [files, rule]);

  const handleRename = useCallback(() => {
    setRenamed(true);
  }, []);

  const handleDownloadScript = useCallback(() => {
    const lines = previewEntries.map(
      (entry) => `rename "${entry.original}" "${entry.newName}"`
    );
    const script = `@echo off\nREM Bulk Rename Script\nREM Generated by Toolsz\n\n${lines.join("\n")}\n\necho Done! Renamed ${previewEntries.length} files.\npause`;
    const blob = new Blob([script], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "rename.bat";
    a.click();
    URL.revokeObjectURL(url);
  }, [previewEntries]);

  const handleDownloadBashScript = useCallback(() => {
    const lines = previewEntries.map(
      (entry) => `mv "${entry.original}" "${entry.newName}"`
    );
    const script = `#!/bin/bash\n# Bulk Rename Script\n# Generated by Toolsz\n\n${lines.join("\n")}\n\necho "Done! Renamed ${previewEntries.length} files."`;
    const blob = new Blob([script], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "rename.sh";
    a.click();
    URL.revokeObjectURL(url);
  }, [previewEntries]);

  const handleReset = () => {
    setFiles([]);
    setRenamed(false);
    setRule(defaultRule);
  };

  const modeTabs: { key: RenameMode; label: string; icon: React.ComponentType<{ className?: string }> }[] = [
    { key: "numbering", label: "Numbering", icon: Hash },
    { key: "date", label: "Date Stamp", icon: Calendar },
    { key: "find-replace", label: "Find & Replace", icon: Search },
    { key: "pattern", label: "Custom Pattern", icon: PenLine },
  ];

  return (
    <div className="min-h-[calc(100vh-8rem)]">
      <div className="max-w-[1200px] mx-auto px-5 md:px-6 lg:px-8 pt-8 sm:pt-12">
        <ToolHero
          icon={PenLine}
          title="Bulk File Renamer"
          description="Rename multiple files at once using logic-based rules — date stamps, sequential numbering, custom patterns, and find & replace. Free, instant, and completely private."
          backHref="/dev-tools"
          backLabel="Back to Developer Tools"
        />
      </div>

      <div className="max-w-[1200px] mx-auto px-5 md:px-6 lg:px-8 py-4 sm:py-8">
        <div className="glass-panel rounded-[16px] p-6 sm:p-8 space-y-5">
          {/* Upload */}
          <FileUpload
            accept="*"
            multiple
            files={files}
            onFilesChange={setFiles}
            label="Drop files here to rename"
            description="Upload multiple files — any format"
          />

          {files.length > 0 && (
            <>
              {/* Mode Tabs */}
              <div>
                <label className="block text-xs font-semibold text-foreground mb-2">Rename Mode</label>
                <div className="flex flex-wrap gap-2">
                  {modeTabs.map(({ key, label, icon: Icon }) => (
                    <button
                      key={key}
                      onClick={() => setRule((r) => ({ ...r, mode: key }))}
                      className={`px-4 py-2 rounded-lg border text-xs font-semibold transition-all flex items-center gap-2 ${
                        rule.mode === key
                          ? "bg-primary-muted border-primary-border text-primary"
                          : "bg-surface-1 border-border text-foreground-secondary hover:bg-surface-2"
                      }`}
                    >
                      <Icon className="w-3.5 h-3.5" />
                      {label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Rule Settings */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {rule.mode === "numbering" && (
                  <>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Prefix</label>
                      <input
                        type="text"
                        value={rule.prefix}
                        onChange={(e) => setRule((r) => ({ ...r, prefix: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="file_"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Suffix</label>
                      <input
                        type="text"
                        value={rule.suffix}
                        onChange={(e) => setRule((r) => ({ ...r, suffix: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="_final"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Start Number</label>
                      <input
                        type="number"
                        value={rule.startNumber}
                        onChange={(e) => setRule((r) => ({ ...r, startNumber: Number(e.target.value) }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        min={0}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Zero Padding</label>
                      <select
                        value={rule.padding}
                        onChange={(e) => setRule((r) => ({ ...r, padding: Number(e.target.value) }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                      >
                        <option value={1}>1 (1, 2, 3...)</option>
                        <option value={2}>2 (01, 02, 03...)</option>
                        <option value={3}>3 (001, 002, 003...)</option>
                        <option value={4}>4 (0001, 0002, 0003...)</option>
                      </select>
                    </div>
                  </>
                )}

                {rule.mode === "date" && (
                  <>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Prefix</label>
                      <input
                        type="text"
                        value={rule.prefix}
                        onChange={(e) => setRule((r) => ({ ...r, prefix: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="backup_"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Date Format</label>
                      <select
                        value={rule.dateFormat}
                        onChange={(e) => setRule((r) => ({ ...r, dateFormat: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                      >
                        <option value="YYYY-MM-DD">YYYY-MM-DD</option>
                        <option value="DD-MM-YYYY">DD-MM-YYYY</option>
                        <option value="MM-DD-YYYY">MM-DD-YYYY</option>
                        <option value="YYYY-MM-DD_HH-mm-ss">YYYY-MM-DD_HH-mm-ss</option>
                      </select>
                    </div>
                  </>
                )}

                {rule.mode === "find-replace" && (
                  <>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Find</label>
                      <input
                        type="text"
                        value={rule.findText}
                        onChange={(e) => setRule((r) => ({ ...r, findText: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="text to find"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Replace With</label>
                      <input
                        type="text"
                        value={rule.replaceText}
                        onChange={(e) => setRule((r) => ({ ...r, replaceText: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="replacement text"
                      />
                    </div>
                  </>
                )}

                {rule.mode === "pattern" && (
                  <>
                    <div className="sm:col-span-2">
                      <label className="block text-xs font-semibold text-foreground mb-1">
                        Pattern — use <code className="bg-primary-muted px-1 rounded text-primary text-[11px]">{`{name}`}</code> <code className="bg-primary-muted px-1 rounded text-primary text-[11px]">{`{n}`}</code> <code className="bg-primary-muted px-1 rounded text-primary text-[11px]">{`{date}`}</code> <code className="bg-primary-muted px-1 rounded text-primary text-[11px]">{`{i}`}</code>
                      </label>
                      <input
                        type="text"
                        value={rule.pattern}
                        onChange={(e) => setRule((r) => ({ ...r, pattern: e.target.value }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground font-mono focus:outline-none focus:ring-2 focus:ring-primary/30"
                        placeholder="{name}_{n}"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Start Number</label>
                      <input
                        type="number"
                        value={rule.startNumber}
                        onChange={(e) => setRule((r) => ({ ...r, startNumber: Number(e.target.value) }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                        min={0}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-foreground mb-1">Padding</label>
                      <select
                        value={rule.padding}
                        onChange={(e) => setRule((r) => ({ ...r, padding: Number(e.target.value) }))}
                        className="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                      >
                        <option value={1}>1 (1, 2, 3...)</option>
                        <option value={2}>2 (01, 02...)</option>
                        <option value={3}>3 (001, 002...)</option>
                        <option value={4}>4 (0001, 0002...)</option>
                      </select>
                    </div>
                  </>
                )}

                <label className="flex items-center gap-3 cursor-pointer sm:col-span-2">
                  <input
                    type="checkbox"
                    checked={rule.keepExtension}
                    onChange={(e) => setRule((r) => ({ ...r, keepExtension: e.target.checked }))}
                    className="w-4 h-4 rounded border-border text-primary focus:ring-primary/30"
                  />
                  <span className="text-sm text-foreground-secondary">Keep original file extension</span>
                </label>
              </div>

              {/* Preview Table */}
              <div>
                <h4 className="text-xs font-semibold text-foreground mb-2">Rename Preview</h4>
                <div className="overflow-x-auto max-h-[300px] overflow-y-auto rounded-xl border border-border">
                  <table className="w-full text-xs">
                    <thead className="sticky top-0 bg-surface-1">
                      <tr className="border-b border-border">
                        <th className="py-2 px-3 text-left font-semibold text-foreground-muted w-12">#</th>
                        <th className="py-2 px-3 text-left font-semibold text-foreground-secondary">Original</th>
                        <th className="py-2 px-3 text-center w-10"></th>
                        <th className="py-2 px-3 text-left font-semibold text-primary">New Name</th>
                      </tr>
                    </thead>
                    <tbody>
                      {previewEntries.map((entry, i) => (
                        <tr key={i} className="border-b border-border/30 hover:bg-surface-1 transition-colors">
                          <td className="py-1.5 px-3 font-mono text-foreground-muted">{i + 1}</td>
                          <td className="py-1.5 px-3 text-foreground-secondary truncate max-w-[200px]">{entry.original}</td>
                          <td className="py-1.5 px-3 text-center">
                            <ArrowRight className="w-3.5 h-3.5 text-primary mx-auto" />
                          </td>
                          <td className="py-1.5 px-3 text-primary font-semibold truncate max-w-[200px]">{entry.newName}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Actions */}
              <div className="flex flex-col sm:flex-row gap-3">
                <button
                  onClick={handleDownloadScript}
                  className="btn btn-primary inline-flex items-center justify-center gap-2 flex-1"
                >
                  <Download className="w-4 h-4" />
                  Download .bat Script
                </button>
                <button
                  onClick={handleDownloadBashScript}
                  className="btn btn-secondary inline-flex items-center justify-center gap-2 flex-1"
                >
                  <Download className="w-4 h-4" />
                  Download .sh Script
                </button>
                <button
                  onClick={handleReset}
                  className="btn btn-secondary inline-flex items-center justify-center gap-2"
                >
                  <RotateCcw className="w-4 h-4" />
                  Reset
                </button>
              </div>
            </>
          )}
        </div>

        {/* Info Cards */}
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="glass-panel glass-panel-info rounded-[16px] p-6 flex items-start gap-5">
            <div className="w-10 h-10 rounded-[14px] bg-gradient-to-br from-indigo-50 to-indigo-100 border border-indigo-200/50 flex items-center justify-center flex-shrink-0">
              <Shield className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h4 className="font-display font-semibold text-foreground text-sm mb-1.5">Logic-Based Renaming</h4>
              <p className="text-foreground-muted text-sm leading-relaxed">
                Not just find-and-replace. Use date stamps, sequential numbering, custom patterns with variables, and find-replace — all with logic rules.
              </p>
            </div>
          </div>
          <div className="glass-panel glass-panel-info rounded-[16px] p-6 flex items-start gap-5">
            <div className="w-10 h-10 rounded-[14px] bg-gradient-to-br from-indigo-50 to-indigo-100 border border-indigo-200/50 flex items-center justify-center flex-shrink-0">
              <Zap className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h4 className="font-display font-semibold text-foreground text-sm mb-1.5">Instant Preview</h4>
              <p className="text-foreground-muted text-sm leading-relaxed">
                See exactly what each file will be renamed to before committing. Download a rename script for Windows (.bat) or Mac/Linux (.sh).
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
